[package]
name = "radrootscore-ios"
version = "0.1.0"
edition = "2024"
authors = ["Radroots Authors"]
rust-version = "1.92.0"
license = "GPL-3.0-or-later"
description = "radroots ios rust wrapper manifest"

[workspace]
resolver = "2"

[workspace.dependencies]
radroots-app-ffi-swift = { path = "../../../../../../foundation/oss/rs/crates/app-ffi-swift" }
